spring:
  application:
    name: scrapepilot-ai

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapepilot
    username: ivan
    password: scrape010203

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true